language: node_js
node_js:
- 5.5.0
install:
- npm install
script:
- webpack --bail --progress --build
sudo: false
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: app.topcoder-dev.com
  local_dir: dist
  on:
    branch: dev
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $QA_AWS_KEY
  secret_access_key: $QA_AWS_SECRET
  bucket: app.topcoder-qa.com
  local_dir: dist
  on:
    branch: qa
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  access_key_id: $MASTER_AWS_KEY
  secret_access_key: $MASTER_AWS_SECRET
  bucket: app.topcoder.com
  local_dir: dist
  on:
    branch: master
env:
  matrix:
  - CXX=g++-4.8
  global:
  # DEV_AWS_KEY
  - secure: ftCAX47TDUjlsnLMmvR/n26CSVwKMulvTGcGH6bkmhksoFVvL1NLaan+OjPwRaFS+KB6YUN3RP4xM80CowRJYIxk77Yu4JMaasJxW8dIjVDLVf5T7vONVgPJWufWGcOq8o9AxhbWr1d/r+H73I6t1aLf9Q6zAWtkCWUxszH3HV2pyRWC4mXikXmqbN1mnjRkAN0ZJLHynYPwVAfE0e0sKKQq/vdkL7gzS6LKuxI7Lbd9SQvn0XWISJTty6ZnzCIJQug+Ra8M+XBJxTq/Gq/G7XuiStGi51d8WJgX0yqKQHBIyVEhQwTTYSf8Lt6ea9VCS4x1RnXUhjv+1DHBAvHn0xL+IJTfhddUqBRORekfFOA0qDGasfnEMDzaJRpfzK+QrDWbDVOTlIG5agbqfhDlollzHf6ePeVN+cYHMAPiZweMx5EGB/+P0TsWCgiaTIVjppqMSorTCebZikwo+O94ttJk2ssFWG+eQ0UcTxjcGcaJlmtrMe+9l3hW7hDjSbdy0ueMF3z7jdIozRe4T34RQuvRCBc141Cuov2c5//j68p5d8iTCRA0Wr3yrXDvewc9sDKNMGtuQHJfLhrRUsgVI0W7zh2strPN+fxq3aJ/tKNQQ2DE3EAAotECcgfJjJYGPMJ4JG7YCJhSTXFWTp0GIePPsv33wcg4VS75k57f8JQ=
  # DEV_AWS_SECRET
  - secure: UHF+v/8TabFZcOzaHHL4Yp739HxQMVlx6DYBhR7fRlpN7Um99ms5r9BS9ERu57XO5f/DFIy88pCiWFPpynmAICe+rIhJtKge0QN0VT3vXXF0hdaMjXmFd0tPcNohJFLXaAq/1OaZWzAqqMaAae+ZyFhKCICzS2q9/t+uQ+cJJcUju+RVUNBbFxqqGLzUC209MqBAKEeBp6YuVfPyVLmqRXKhXKDgoD5Lups0xmN6o0oH+MuRZu6X0d16sNrkvsNoIoEGN5JFxvbj/HYgJkQhq9pOeTWu6sKm3XoCchYlGk0OVygWxum00qcLqVJHoNrywGLwk6hHXs+vxnjICf7x662sbaXam410Z2S2l8Pt+s+QxGL9yqfUsMs9TczMZg+M7ulA+DlajoOo0LrpFjhuQc1g733GnLpDD4tvknqgtZ+l7InSc/WgzWP7slPkSF3S///+rg+ldBKZYtOAWhNJYCU0GxVXTKkOqfvlVVyG2L1qR/AtttMIDzui9xBQWKNOtmPhSz2R6dyJs6uSzypcICWpxWXyeQ9JZSL+f5vdG+3pDKkDfMKNRRwVK3GbgmQdWKdJVUeLVbWGx7KAL938VOfiAUp6w0QM73CJmqqghUe/nkEmiU9b9N/mpUZqKdDDCupSqUW0XJRv5xQZT+FLh17qCTqfhKMxLSVFErG+M6Q=
  # QA_AWS_KEY
  - secure: lpdUndFkKU1MbQZ7pT7ke4XWItHNYCDSt8vInYqiBHByK42//DzUoUQhP3B8QVf8teKBnXnbbJGl01SpUgd1+ZdepI1ksa06KOfeyRrZ3cmFh3UBR5RWDYmxZxnJFgzmL3tMTEfzImO2Khd0CLIdIOAwhRXtI2Z5Ipwqnu295X8=
  # QA_AWS_SECRET
  - secure: aIuFS/dIGZbWIBUNRrw1d1Z/RJHIafYTyNerx6QWo/ENsZyBKC2FlD1pFXd9AZkyYuF99wZxgKsBoiYpTraLdJ26K4YQYQIRw/5HsWYZqukI8yctsZ6NdvZkXKncZbMlW5KJADUGHHa+ktzmqXlwS0qO00HlSaTwHCr15XKoS/M=
  # MASTER_AWS_KEY
  - secure: gpEtWMYBfF8NvC+nfLKw6OtONISssGMyzJ7qyXPIviaaRasnVD9nArlEozBw/qrhcYA0TPFMg7ZQq5NipkOIw2RZUgEtpKHD+hmaO7/apE3RtX85QY44wFat/VydQWl2U9EodS9XcdsKEDSghgnehbB0mO6piuvnC6reQwo1Z/0=
  # MASTER_AWS_SECRET
  - secure: Oxu8D8CFk6EDLi/RPXRM3Peb0SVzVWApz3IKvROXWD8IbOfVBgvyaOdhhh2q10V085kkcAMayYNSifRd4ZhpTOJdQF/UoaczFIekhNDq/zPZLEf9j/EgJD9oWGkgIP9ct3KWSphtUChcNTvNHAlC+4kGMo3djZBe/BCkgyiwlZE=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
